### ISSUE TITLE
Doc: How to make it work with resolver

### ISSUE THREAD

**Issue by vfonic** [RStankov/SearchObjectGraphQL#17]
I've had some issues making SearchObject work with resolver.

For some unexplicable reason neither SearchObject nor SearchObjectGraphQL were loaded.

```rb
$ rails console
> SearchObject
NameError: uninitialized constant SearchObject
from /Users/viktor/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant'
> require 'search_object'
true
> SearchObject
SearchObject
> require 'search_object/plugin/graphql'
true
```

After adding these two requires on top of my resolver, the search finally worked.

Here's the full source code for resolver:

```rb
require 'search_object'
require 'search_object/plugin/graphql'

module Resolvers
  class EventResolver
    include SearchObject.module(:graphql)

    type Types::EventType.connection_type, null: false

    scope { object.respond_to?(:subscribed_events) ? object.subscribed_events : object.events }

    option(:from_date, type: Types::DateType) { |scope, value| scope.after(value) }
  end
end
```

One thing to note: `from_date` is visible as `fromDate` argument in GraphQL schema. This is what I want, but just something to keep in mind.

@RStankov do you think anything from here should be added to the README.md? Or perhaps the gem should autoload the missing constants/modules?

I'm using rails (5.2.3) and graphql (1.9.9).

PS I don't use 'spring' gem in my app.

**Comment by RStankov** [comment]
I think this should be added to README. Because I don't want to force autoloading things which won't be used from search object to the users.

**Comment by vfonic** [comment]
I find it very rare that gems don't autoload main files/constants. Isn't the whole of `gem 'gem_name', require: false` to _opt-in_ for not autoloading things?

**Comment by RStankov** [comment]
Yes, the but most people don't think about this and get a lot of unneeded coded. I know it is a bit inconvenient. Will update README to explain this. 

Thanks for mentioning it.

**Comment by RStankov** [comment]
✅Updated the README

**Comment by ItsRhen** [comment]
The naming convention for option declaration needs some love. I just killed 3 hours because the example has them camelCase and they'd only run when snake_case.

**Comment by RStankov** [comment]
@ItsRhen sorry that this happened. Which example you are referring to and how do you think we can improve on this example?
