### ISSUE TITLE
unknown keyword: field

### ISSUE THREAD

**Issue by ardinusawan** [RStankov/SearchObjectGraphQL#20]
When I updated graphql-ruby gem from 1.9.15 to 1.9.16 I got error `unknown keyword: field`

I think this related to this [breaking changes](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-1)

Please help 🙏

**Comment by ardinusawan** [comment]
Maybe the fix will be like [this](https://github.com/RStankov/SearchObjectGraphQL/pull/21)

**Comment by RStankov** [comment]
You are right 10x, merged and I'm releasing a fix

**Comment by ardinusawan** [comment]
Closed due [merged](https://github.com/RStankov/SearchObjectGraphQL/pull/21)
