### ISSUE TITLE
Resolver options ignore prepare option 

### ISSUE THREAD

**Issue by hschne** [RStankov/SearchObjectGraphQL#26]
I'm facing an issue where I am adding several arguments to a field. Specifically, I am trying to filter a collection by a list of statuses, and users may pass `null` or an empty array. In this case I want to use the default value. 

## TL;DR
'Normal' resolvers allow me to use the `prepare: ...` argument, but that doesn't seem to work with SearchObjectGraphQL.

## In Detail

My resolver looks similar to this: 

```ruby
module Resolvers
  class BookResolver < GraphQL::Schema::Resolver
    include SearchObject.module(:graphql)

    type [Types::BookType], null: false

    scope { Books.all }

    option(:status,
           type: [Types::Enums::BookStatus],
           default_value: [:new, :published],
           scope, statuses|
        scope.where(status: statuses)
      end
    end
```

Because the status is optional, users are allowed to pass null or empty arrays in the query. As far as I understand this is part of the [GraphQL spec and intentional](https://github.com/graphql/graphql-spec/issues/542), so... :shrug: 

```graphql
query books {
  books(status: null){
   ...
  }
}
```

Because filtering by, well, `null` makes no sense in this context, I would like to fall back to the default value. GraphQL Ruby provides the handy prepare method for this (see [here](https://graphql-ruby.org/fields/arguments.html)). The resolver below would throw an error if called with `numbers: null` without the prepare method, but like so it works: 

```ruby
field :sum, null: false, resolver: Resolvers::SumResolver

module Resolvers
  class SumResolver < GraphQL::Schema::Resolver
    type Integer, null: false

    argument :numbers, [Integer], required: false, prepare: ->(value, _) { value || [] }

    def resolve(numbers: [])
      numbers.sum
    end
  end
end
```

```graphql
query sum {
  sum(numbers: null){
   ...
  }
}
```

However, if I create a corresponding search object, this no longer works :cry: 

```ruby
module Resolvers
  class SumResolver < GraphQL::Schema::Resolver
    include SearchObject.module(:graphql)

    type Integer, null: false

    scope { [] }

    option :numbers, type: [Integer],
                     default_value: [],
                     required: false,
                     prepare: ->(value, _) { value || [] } do |_, value|
      value.sum
    end
  end
end
```

I'm assuming that this is the case because the plugin overwrites `resolve_with_support`, and does not use the default resolve mechanism for resolving arguments. Do you think this could be fixed?

Would be happy to open a PR if you reckon this would be doable :)

**Comment by hschne** [comment]
P.S. It seems that [there are plans ](https://github.com/rmosolgo/graphql-ruby/issues/2749) to deprecate `prepare`, so I'm not 100% sure if its worth looking into

**Comment by RStankov** [comment]
Doesn't SearchObject [default value](https://github.com/RStankov/SearchObjectGraphQL#default-values) works? 

```
argument :numbers, [Integer], required: false,  default: []
```

**Comment by hschne** [comment]
> Doesn't SearchObject default value works?

Sadly it does not. This is discussed in [#2864](https://github.com/rmosolgo/graphql-ruby/issues/2864)

To be honest, the workaround proposed there works well enough - so its definitely not a big deal that `prepare` doesn't work.

**Comment by RStankov** [comment]
This `default` is not part of GraphQL-ruby it comes from SearchObject.

```ruby
option(:numbers, type: [Integer], default: []) { |_, value| value.sum }
```

**Comment by hschne** [comment]
True, confused that with `default_value` :see_no_evil: 

Still, doesn't make any difference. This uses `default` and causes the error described above still: 
```ruby
class SumResolver < GraphQL::Schema::Resolver
  include SearchObject.module(:graphql)

  type Integer, null: false

  scope { [] }

  option :numbers, type: [Integer],
       default: [],
       required: false do |_, value|
    value.sum
  end
end

**Comment by RStankov** [comment]
I see, you will have to do `Array(value).sum` to force it to array.

**Comment by hschne** [comment]
True, thats good enough for me :)
