### ISSUE TITLE
How to include authentication for the search

### ISSUE THREAD

**Issue by joardar-aditya** [RStankov/SearchObjectGraphQL#27]

**Comment by RStankov** [comment]
Hey, @joardar-aditya can you give me more context around the issue?

In general `SearchObject` include reference to GraphQL `context` and you can access it.

**Comment by joardar-aditya** [comment]
@RStankov  I wanted to restrict some queries only for certain type of users.... where can i put that logic, i mean my authenticate_function.

**Comment by RStankov** [comment]
You have access to `context` in search object where you can store your current user and then authenticate there:

```ruby
option :price, String, with: :filter_by_price

def filter_by_price(scope)
  if context.current_user.admin?
    scope.where('price > :price', :price)
  else
    scope
  end
end
```
