### ISSUE TITLE
ruby-grahpql 1.12.0 update breaks how scopes are returned

### ISSUE THREAD

**Issue by Postmodum37** [RStankov/SearchObjectGraphQL#28]
Example:

```ruby
  def apply_order_with_recent(scope)
    scope.order 'created_at DESC'
  end
```

Before version 1.12.0 `scope` is an instance of `ActiveRecord::Relation`. After - scope is an instance of `Array` class.

**Comment by RStankov** [comment]
@Postmodum37, I can reproduce. Can you give me the full example?
