### ISSUE TITLE
Overridden private GraphQL API method: `#resolve_with_support`

### ISSUE THREAD

**Issue by thayol** [RStankov/SearchObjectGraphQL#40]
Currently in [lib/search_object/plugin/graphql.rb](https://github.com/RStankov/SearchObjectGraphQL/blob/8cbca8f7b2c7ba084b73a3c71a210dd737e63964/lib/search_object/plugin/graphql.rb), we have this:
```rb
      # NOTE(rstankov): GraphQL::Schema::Resolver interface
      # Documentation - http://graphql-ruby.org/fields/resolvers.html#using-resolver
      def resolve_with_support(args = {})
        self.params = args.to_h
        results
      end
```

This overrides `#resolve_with_support` which is [part of the private API](https://www.rubydoc.info/gems/graphql/GraphQL%2FSchema%2FResolver:resolve_with_support). This has some interesting implications, like `#authorized?` never getting called for resolvers implementing `SearchObject`.

Are we missing a `super` call somewhere?
Or is it possible that we should override `#resolve` and not `#resolve_with_support`?

**Comment by RStankov** [comment]
When I was building the gem `resolved` didn't work as expected. Now it does. Thanks 🙌
