### ISSUE TITLE
Using new syntax with `connection_type` type

### ISSUE THREAD

**Issue by AlanFoster** [RStankov/SearchObjectGraphQL#9]
Hey, I've just tried updating to the latest GraphQL Ruby Syntax and I've had no luck with `.connection_type` being specified:

```ruby
module Types
  class QueryType < GraphQL::Schema::Object
    field :categories_working, [Types::CategoryType], function: Resolvers::CategorySearch

    # Doesn't appear to work:
    field :categories_not_working, Types::CategoryType.connection_type, function: Resolvers::CategorySearch
  end
end
```

When run the following query for `categories_not_working` within graphiql it responds with a stack trace:

![image](https://user-images.githubusercontent.com/1271782/50741983-edc43380-11fc-11e9-9260-0a48e77334de.png)

Text:

```json
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<NoMethodError: undefined method `edge_nodes' for #<Category::ActiveRecord_Relation:0x00007faf1cb71da8>>",
  "traces": {
```
But not supplying `connection_type` works as expected:

![image](https://user-images.githubusercontent.com/1271782/50741991-ff0d4000-11fc-11e9-94ab-622c1e32098c.png)

**Comment by AlanFoster** [comment]
I've created a branch here as an example of the updated syntax, and the two queries:

https://github.com/RStankov/SearchObjectGraphQL/compare/master...AlanFoster:9-updated-connection-type-syntax-issue?expand=1

Any help would be appreciated :+1:

**Comment by RStankov** [comment]
Hey thanks for reporting. Will try to fix this in this weeked.

**Comment by RStankov** [comment]
Hey, the solution is to change the type in the search resolver to `Types::CategoryType.connection_type`:

```ruby
module Resolvers
  class CategorySearch < Resolvers::BaseSearchResolver
    type Types::CategoryType.connection_type
```
